//
//  CountryRecommendation.swift
//  FoundationModelsAssistantAI
//
//  AI-DRIVEN SWIFT ARCHITECTURE
//

import FoundationModels

/// A structured travel recommendation generated by the language model.
///
/// Annotated with `@Generable` so `LanguageModelSession` can produce instances
/// directly. Each `@Guide` annotation constrains the model's output for that
/// property, ensuring consistent and well-formed travel data.
///
/// Structured output is preferred here because a country recommendation
/// contains heterogeneous fields (strings, arrays, nested objects) that
/// would be difficult to parse reliably from free-form text.
@Generable
struct CountryRecommendation {

    /// The name of the recommended country.
    @Guide(description: "The name of the country")
    let name: String

    /// A brief description of why this country is worth visiting.
    @Guide(description: "A brief compelling description of why to visit this country")
    let overview: String

    /// Notable cities within the country, constrained to 2-5 entries.
    @Guide(description: "The list of famous cities to visit", .count(2...5))
    let cities: [City]

    /// The optimal season or period for travel.
    @Guide(description: "Best time of year to visit (e.g., 'Spring and Fall', 'Year-round')")
    let bestTimeToVisit: String

    /// Key attractions and points of interest in the country.
    @Guide(description: "Main attractions and highlights of the country")
    let highlights: [String]

    /// Traditional dishes or culinary experiences to try.
    @Guide(description: "Traditional dishes or food experiences to try")
    let cuisine: [String]

    /// An approximate budget category for the trip.
    @Guide(description: "Estimated budget level: 'Budget-friendly', 'Moderate', or 'Luxury'")
    let budgetLevel: String

    /// The primary languages spoken in the country.
    @Guide(description: "Primary language(s) spoken")
    let languages: [String]

    /// The local currency used for transactions.
    @Guide(description: "Currency used in the country")
    let currency: String
}

/// A city within a ``CountryRecommendation``, with attractions and logistics.
///
/// Annotated with `@Generable` to support nested structured generation.
/// The `recommendedDays` property uses a `@Guide` range constraint to
/// keep the value within a realistic range.
@Generable
struct City {

    /// The name of the city.
    @Guide(description: "The name of the city")
    let name: String

    /// A summary of what makes this city notable or worth visiting.
    @Guide(description: "What makes this city special or worth visiting")
    let description: String

    /// Must-see landmarks and attractions.
    @Guide(description: "Must-see attractions in this city")
    let attractions: [String]

    /// Suggested number of days to spend, constrained to 1-30.
    @Guide(description: "Recommended duration of stay in days", .range(1...30))
    let recommendedDays: Int

    /// Activities or experiences unique to this city.
    @Guide(description: "Notable activities or experiences unique to this city")
    let activities: [String]
}
