//
//  Quiz.swift
//  FoundationModelsAssistantAI
//
//  AI-DRIVEN SWIFT ARCHITECTURE
//

import FoundationModels

/// A structured quiz generated by the language model.
///
/// Annotated with `@Generable` so `LanguageModelSession` produces a fully typed
/// quiz object. The `difficulty` property uses `@Guide(.anyOf(...))` to constrain
/// the model to one of three valid difficulty levels.
///
/// Structured output ensures each question includes exactly one correct answer
/// index and an explanation, which would be error-prone to extract from free-form text.
@Generable
struct Quiz {

    /// The subject or topic of the quiz.
    @Guide(description: "The title of the quiz topic")
    let topic: String

    /// The difficulty tier, constrained to "Beginner", "Intermediate", or "Advanced".
    @Guide(description: "Difficulty level", .anyOf(["Beginner", "Intermediate", "Advanced"]))
    let difficulty: String

    /// The list of multiple-choice questions that comprise the quiz.
    @Guide(description: "List of multiple-choice questions")
    let questions: [QuizQuestion]

    /// The estimated completion time in minutes.
    @Guide(description: "Estimated time to complete in minutes")
    let estimatedDuration: Int
}

/// A single multiple-choice question within a ``Quiz``.
///
/// Annotated with `@Generable` to support nested structured generation.
/// The `correctAnswerIndex` provides a machine-readable answer key alongside
/// a human-readable `explanation`.
@Generable
struct QuizQuestion {

    /// The question prompt displayed to the user.
    @Guide(description: "The question text")
    let question: String

    /// The four answer choices for this question.
    @Guide(description: "Four possible answers")
    let options: [String]

    /// The zero-based index of the correct answer within `options`.
    @Guide(description: "The index of the correct answer (0-3)")
    let correctAnswerIndex: Int

    /// A rationale explaining why the correct answer is right.
    @Guide(description: "Explanation of why this answer is correct")
    let explanation: String
}

