//
//  StoryIdea.swift
//  FoundationModelsAssistantAI
//
//  AI-DRIVEN SWIFT ARCHITECTURE
//

import FoundationModels

/// A structured story outline generated by the language model.
///
/// Annotated with `@Generable` so `LanguageModelSession` returns a typed
/// narrative structure. This ensures the model produces all required story
/// elements (characters, plot points, conflict) in a consistent format
/// rather than unstructured prose.
@Generable
struct StoryIdea {

    /// The title of the story.
    @Guide(description: "An engaging title for the story")
    let title: String

    /// The literary genre (e.g., "Science Fiction", "Mystery").
    @Guide(description: "The genre of the story (e.g., 'Science Fiction', 'Mystery', 'Romance')")
    let genre: String

    /// A one- or two-sentence logline summarizing the story.
    @Guide(description: "A compelling premise or logline for the story")
    let premise: String

    /// The main characters in the story, each with role and motivation details.
    @Guide(description: "Main characters with brief descriptions")
    let characters: [Character]

    /// Ordered plot points or story beats that form the narrative arc.
    @Guide(description: "Key plot points or story beats")
    let plotPoints: [String]

    /// The primary conflict driving the story forward.
    @Guide(description: "The main conflict or challenge in the story")
    let centralConflict: String

    /// A proposed resolution or ending for the story.
    @Guide(description: "Possible ending or resolution")
    let suggestedEnding: String
}

/// A character within a ``StoryIdea``, described by role and motivation.
///
/// Annotated with `@Generable` to support nested structured generation
/// inside the parent ``StoryIdea`` schema.
@Generable
struct Character {

    /// The character's name.
    @Guide(description: "Character's name")
    let name: String

    /// The narrative role (e.g., "Protagonist", "Antagonist", "Mentor").
    @Guide(description: "Character's role in the story (e.g., 'Protagonist', 'Antagonist', 'Mentor')")
    let role: String

    /// A brief description of the character's personality traits.
    @Guide(description: "Brief personality description")
    let personality: String

    /// The character's primary goal or driving motivation.
    @Guide(description: "Character's main motivation or goal")
    let motivation: String
}

